#!/bin/bash
set -e
export JCD_NEW_ROOT=$(dirname $(readlink -f $0))
export JCD_NEW_LIBS=$JCD_NEW_ROOT/.jcd-new
export JCD_NEW_VERSION="0.0.1-pre"

main() {
    source "$JCD_NEW_LIBS/jcd-new.bashlib" #include the common library so everything in here can execute.
    if [[ $1 == version || $1 == help ]]; then
        bash "$JCD_NEW_LIBS/jcd-new-$1" ${*:2}
    elif [ "$(is_in_git_repo)" == true ]; then
        command="$JCD_NEW_LIBS/jcd-new-$1"

        if [[ -f "$command" ]]; then
        export GIT_VER_REPO_ROOT="$(get_repo_root)"
        export GIT_VER_REPO_BRANCH_NAME="$(get_branch_name)"
        export GIT_VER_REPO_VERSION="$(get_version)"
        export GIT_VER_REPO_LATEST_TAG="$(get_tag)"
            bash "$command" "${*:2}"
        else
            echo >&2 "Unknown command: $1."
            bash "$JCD_NEW_LIBS/jcd-new-help"
            exit 1
        fi;
    else
        echo "The current directory isn't a git working tree. You must be in a git working tree to run this command"
        exit 2
    fi;
}

main "$@"