#!/bin/bash
set -e

if [[ "$1" == "" ]]; then
cat << EOF | less
usage: jcd-new [command] [command arguments]
For more details on the individual commands type jcd-new help [command]

List of commands:
classlib             : Creates a new .NET Standard class library. See jcd-new help classlib for details.

locations            : Lists the directory locations jcd-new is currently using.

version              : Display the version number.

--version            : An alias for version.

help                 : Displays this help information.

help <command>       : Displays command specific help.

EOF
else
    #( export GIT_VER_VERSION; "JCD_NEW_DIR/jcd-new-help-$ 1" 2>&1 /dev/null || { echo >&2 "Cannot find help for command: $1."; exit 1; } )
    if [[ -f "$JCD_NEW_LIBS/jcd-new-help-$1" ]]; then
        ( export GIT_VER_VERSION; bash "$JCD_NEW_LIBS/jcd-new-help-$1" )
    else 
        echo >&2 "Couldn't find help for: $1."; 
        exit 1; 
    fi;
fi;